export const GET_PORT_IMAGES = "GET_PORT_IMAGES";
export const CHANGE_CURRENT_SECTION = "CHANGE_CURRENT_SECTION";
export const SET_LARGE_IMG = "SET_LARGE_IMG";
export const SET_LOADING = "SET_LOADING";
